spring:
  application:
    name: config-bus-server
  rabbitmq:
    host: 192.168.3.26
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/pangzl/config-repo.git
          # 强制拉取资源文件
          force-pull: true
#          search-paths:
#          username:
#          password:

server:
  port: 60002

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.26:20000/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

